a=int(input("Enter First value"))
b=int(input("Enter Second value"))
print("The Result=",a+b)
print("The Result=",a-b)
print("The Result=",a*b)
print("The Result=",a/b)
print("The Result=",a%b)
